### ISSUE TITLE
Re-enable CBMC on self-hosted runner

### ISSUE THREAD

**Issue by hanno-becker** [pq-code-package/mlkem-c-aarch64#117]
We're hitting resource limitations for the free Ubuntu runner which makes CBMC fail in CI. #113 disables it for now.

We need to discuss whether it's worth re-enabling it on a self-hosted (EC2) runner.

**Comment by hanno-becker** [comment]
The CBMC run itself is quick at the moment, but as I remember the nix build takes quite some time, even though we do use the nix cache.

I'd be inclined to open a PR using a medium-capacity EC2 runner for this, running it a few times to gauge the runtime and cost, and then decide if it's worth it.

**Comment by hanno-becker** [comment]
This is currently blocked on a compilation error on CBMC 6.2.0 on ubuntu-latest aarch64 machines. @rod-chapman This is still open right?

**Comment by rod-chapman** [comment]
Yes... CBMC team are looking at the build failure on Aarch64 machines...

**Comment by hanno-becker** [comment]
@rod-chapman Is this resolved with CBMC 6.3.1 (#150)?

**Comment by hanno-becker** [comment]
Fixed in https://github.com/pq-code-package/mlkem-c-aarch64/pull/154
