### ISSUE TITLE
Consider alignment of typedefs and struct fields

### ISSUE THREAD

**Issue by rod-chapman** [pq-code-package/mlkem-c-aarch64#145]
Measurable performance gains can be achieved by aligning large data items (e.g. polynomial arrays) on the boundary of a CPU's L1 D-Cache line, which is typically 64 bytes (Graviton 2) or other power of two.

Consider defining macro PREFERRED_DCACHE_ALIGNMENT with a sensible default value, but possibly overridden for particular micro-architectures.

use C11's <stdalign.h> definitions that define the "alignas()" macro for objects and struct fields.

**Comment by hanno-becker** [comment]
Fixed by #151
