### ISSUE TITLE
Skipped CI jobs have wrong name

### ISSUE THREAD

**Issue by mkannwischer** [pq-code-package/mlkem-c-aarch64#155]
![image](https://github.com/user-attachments/assets/654386ab-db83-474a-9207-a20c651fd30b)

See, e.g., https://github.com/pq-code-package/mlkem-c-aarch64/pull/144
https://github.com/pq-code-package/mlkem-c-aarch64/actions/runs/10988042686/job/30503873249?pr=144

**Comment by potsrevennil** [comment]
There is a discussion on github community here
https://github.com/orgs/community/discussions/13261

It seems like it's currently not possible to get reid of this issue
