### ISSUE TITLE
Running format errors in x86_64-linux-cross-ci shell

### ISSUE THREAD

**Issue by mkannwischer** [pq-code-package/mlkem-c-aarch64#157]
If I run 
```
nix develop .#x86_64-linux-cross-ci
```

(which I understand is the only way to get cross-compilation from x86 to work right now -- this should be documented btw), and then run `format` for formatting the code, I get 
```
$ format
info Formatting nix files
/home/mjk/git/mlkem-c-aarch64/scripts/format: line 22: nixpkgs-fmt: command not found
```

**Comment by potsrevennil** [comment]
sorry, maybe I should add some description for the nix shells
`x86_64-linux-cross-ci` is meant to be run on ci, 
while `x86_64-linux-cross` is meant to be run locally, which included the linters in the shell.
