### ISSUE TITLE
Consider adoption of clang-format instead of astyle

### ISSUE THREAD

**Issue by rod-chapman** [pq-code-package/mlkem-c-aarch64#180]
I would like to team to consider replacing the use of "astyle" with clang-format.

The latter has much wider acceptance and use within the community, and is used in significant upstream projects such as AWS-LC. If we adopt clang-format, it will remove a potential objection to those libraries adopting our code.

A strawman plan for discussion. The first steps are two-way doors, and could be implemented immediately.

1. Add "clang-tools" to our NIX environment configuration.
2. Add a proposed ".clang-format" config file to the root directory of the repo. Proposal: adopt the .clang-format file from AWS-LC initially.
3. Add options to our "format" and "lint" scripts to use clang-format instead of astyle.
4. Make the change. Reformat all code, update the scripts to default to clang-format, and update the CI scripts accordingly. All tests and proofs must pass. CBMC contracts must remain readable.
5. Update developer's local editors-of-preference to adopt clang-format (e.g. run clang-format on save for all C code in your favourite IDE, EMACS, vi etc.) and C language mode auto-formatting etc. See https://clang.llvm.org/docs/ClangFormat.html for notes on integration with various editors and IDEs.
6. Also consider use of "git clang-format" integration.
7. Retire and remove astyle from scripts and NIX env.

**Comment by hanno-becker** [comment]
I prefer the tool that makes integration into other projects simplest. If that's clang-format, let's go with it. If we change our mind in the future, we just revert -- it's a two way door. I don't think we should make the effort of maintaining two options for astyle vs. clang.

@rod-chapman Can you open a draft PR?

**Comment by mkannwischer** [comment]
I agree with switching to clang-format. We used astyle mostly because we knew how to work with it in CI from PQClean.

I am unhappy with the most recent versions of astyle doing some very awkward formatting anyway, so I am personally very happy to switch.

Thanks for bringing this up @rod-chapman and volunteering to open a PR.
