### ISSUE TITLE
clang-format CI does not catch formatting mismatches

### ISSUE THREAD

**Issue by hanno-becker** [pq-code-package/mlkem-c-aarch64#193]
Since the switch to `clang-format`, the CI does not catch wrongly formatted files anymore: It does produce warnings, but the scripts don't fail.

**Comment by rod-chapman** [comment]
Thanks for reporting this. I will investigate

**Comment by rod-chapman** [comment]
I think we need 
```
-checkerr "Lint C" "$(clang-format $(git ls-files ":/*.c" ":/*.h") --dry-run)"
+checkerr "Lint C" "$(clang-format $(git ls-files ":/*.c" ":/*.h") --Werror --dry-run)"
```
in scripts/ci/lint
