### ISSUE TITLE
Tests scripts do not work out of the box on x86

### ISSUE THREAD

**Issue by mkannwischer** [pq-code-package/mlkem-c-aarch64#198]
We recently started adding x86 and AVX2 support. 
However, our test scripts are not supporting that very well. 

In the default shell (`$ nix develop`), if I type: `$ tests func` I get 
```
INFO  > Functional Test
INFO  > make CROSS_PREFIX=aarch64-unknown-linux-gnu- mlkem OPT=1
make: aarch64-unknown-linux-gnu-gcc: No such file or directory
make: *** [mk/rules.mk:16: test/build/fips202/fips202.c.o] Error 127
ERROR > make failed: 2
```

Instead I have to type `tests nistkat -cp '' --cflags '-mavx2 -mbmi2 -mpopcnt'`

We should by default build for the current platform and only try cross-compiling when the user asks for it.

**Comment by hanno-becker** [comment]
This has been fixed by @potsrevennil  in #218
