### ISSUE TITLE
Enforce SPDX check 

### ISSUE THREAD

**Issue by cothan** [pq-code-package/mlkem-c-aarch64#26]
SPDX should be automatically enforced in Github Actions.

**Comment by mkannwischer** [comment]
I've implemented it here: https://github.com/pq-code-package/mlkem-c-embedded/pull/29

**Comment by hanno-becker** [comment]
@mkannwischer Can this be closed, then?

**Comment by cothan** [comment]
ah, this has not done in `mlkem-c-aarch64`.

**Comment by hanno-becker** [comment]
@cothan Right, I misread. Can you port https://github.com/pq-code-package/mlkem-c-embedded/pull/29?
