### ISSUE TITLE
Setup native and emulated test CI

### ISSUE THREAD

**Issue by mkannwischer** [pq-code-package/mlkem-c-aarch64#27]
https://github.com/pq-code-package/mlkem-c-aarch64/pull/22 adds native test.

In addition to that I'd like to add support for cross-compilation and testing in qemu. That should also allow running the tests in the Github CI. 
We do have something similar in https://github.com/slothy-optimizer/pqax that could give some inspriation. 
There is CI there too: https://github.com/slothy-optimizer/pqax/pull/4

**Comment by cothan** [comment]
Good idea. After #22 merge I will add a build test, also hashsum to ensure the correctness.

**Comment by hanno-becker** [comment]
Once we integrate AArch64 assembly, #22 will need _updating_ rather than amending, right?

**Comment by hanno-becker** [comment]
So, what we want for the test CI is:
* Native tests on AArch64 Linux runners. @ryjones to provide access to BuildJet Arm runners for this.
* Emulated tests on x86 Linux runners. @potsrevennil you're on this, as I understand?
* Native tests on Mac. Done in #44 by @potsrevennil 
@mkannwischer Agree?

**Comment by potsrevennil** [comment]
Hi, yes I'm on emulated tests on x86 linux runners

**Comment by mkannwischer** [comment]
Yes, that sounds good to me!

**Comment by hanno-becker** [comment]
- [ ] Native tests on AArch64 Linux runners. Done in https://github.com/pq-code-package/mlkem-c-aarch64/pull/49
- [ ] Native tests on Mac. Done in https://github.com/pq-code-package/mlkem-c-aarch64/pull/44 
- [ ] Cross-compilation on x86 Linux runners: Build. Done in #45 
- [ ] Cross-compilation on x86 Linux runners: Test.
