### ISSUE TITLE
CBMC: Strengthen spec for `montgomery_reduce()`

### ISSUE THREAD

**Issue by hanno-becker** [pq-code-package/mlkem-c-aarch64#280]
**Issue:** The current contract for `montgomery_reduce()` only guarantees that the output is within int16 bounds. This is not sufficient to prove the correctness of the matrix-vector base multiplication, which needs to accumulate up to `MLKEM_K` many such reductions. Also, the precondition for `montgomery_reduce()` is different depending on whether it is used for `fqmul()` or `basemul_cached()`.

**Task:** Introduce _two_ contracts for `montgomery_reduce()`, one suitable for application in `fqmul()`, the other suitable for base multiplication. Guard them by preprocessor macros so that in any higher-level CBMC proof, we can choose which spec to pick (as far as I see, we never need both at the same time).

**Comment by rod-chapman** [comment]
I would just have two functions rather than messing with pre-processor macros to "select" the pre- and post-condition. Code size increase will be minimal.

**Comment by hanno-becker** [comment]
@rod-chapman See https://github.com/pq-code-package/mlkem-c-aarch64/pull/292
