### ISSUE TITLE
Remove libnistrng.a and librng.a

### ISSUE THREAD

**Issue by hanno-becker** [pq-code-package/mlkem-c-aarch64#286]
**Issue:** An `.a` file, to me, indicates a piece of general-purpose functionality that is ready to be linked into multiple application contexts. Our build process generates `librng.a`, containing the _insecure_ `randombytes()` function which we do _not_ wish users to link against outside of testing. This insecure `randombytes()` being packaged into an `.a` increases the risk of people linking against it in a production context.

**Task:** Don't generate `librng.a` as an intermediate artifact, but just add `notrandombytes/randombytes.c` to the source tree for the relevant test binaries.

**Comment by hanno-becker** [comment]
@mkannwischer Do you agree?

**Comment by mkannwischer** [comment]
Agree - `librng.a` is misleading. This is an artifact from how we setup the build system in the early days. Let's remove that.
