### ISSUE TITLE
Add internal interface to 4-way Keccak and implement C-fallback

### ISSUE THREAD

**Issue by hanno-becker** [pq-code-package/mlkem-c-aarch64#35]
Partly implements: #33 

Acceptance criteria:
- [ ] The reference implementation is modified to leverage an internal C interface to a 4-way parallel Keccak permutation.
- [ ] The interface is implemented by fallback to the standard 1-way Keccak permutation in C.

Adding AArch64 assembly for 4-way parallel Keccak is _not_ part of this issue.

**Comment by hanno-becker** [comment]
@cothan Do you have time to give this some thought?

**Comment by cothan** [comment]
I made a version of `gen_matrix` work at compile time for Keccak x3 and x4 based on the defined `KECCAK_WAY`. 

The idea is naive, I consider the matrix in `gen_matrix` as 1d array, apply KECCAK_WAY, and feed to `rej_uniform`. For the number of left over vectors less than KECCAK_WAY will fall back to 1-way Keccak version (can use switch/case to select the best left over x2, x3, x4...etc). 

Is it something worthwhile to implement? 
I think the interface you want would be some abstract API on top of x2,....x8-way Keccak at runtime.
