### ISSUE TITLE
Complete CI even when individual components fail

### ISSUE THREAD

**Issue by hanno-becker** [pq-code-package/mlkem-c-aarch64#48]
The current CI setup stops as soon as a single check fails. For example, if linting fails, it won't get to the KAT tests.

@potsrevennil Could you change this behavior so that all checks are run and a summary of failed/successful steps is printed in the end?

**Comment by cothan** [comment]
I agree. Our CI become more complex, and nix setup time take a while as well. I think what @hanno-becker  said is the right approach.
