### ISSUE TITLE
Can we use bsd brace style please for compatibility with CBMC contracts?

### ISSUE THREAD

**Issue by rod-chapman** [pq-code-package/mlkem-c-aarch64#59]
I would like to propose that we switch astyle's indenting mode from "google" to "bsd".

The "google" style places the opening brace on the same line as the preceeding construct, so it appears on the same line as the final term of a loop invariant contract for CBMC. For example, formatting poly.c yields:

```
    for (size_t i = 0; i < KYBER_N / 8; i++)
        __CPROVER_assigns(i, u, __CPROVER_object_whole(t), __CPROVER_object_whole(r))
        __CPROVER_loop_invariant(i <= KYBER_N) {
```
which makes it hard to edit the invariant without accidentially losing or mis-placing the opening brace.

With "bsd" style, this comes out as:

```
    for (size_t i = 0; i < KYBER_N / 8; i++)
        __CPROVER_assigns(i, u, __CPROVER_object_whole(t), __CPROVER_object_whole(r))
        __CPROVER_loop_invariant(i <= KYBER_N)
    {
```
so that lines of the invariant can be added, removed or edited without fear of damaging the location of the brace.

**Comment by hanno-becker** [comment]
How much of an issue is this given that we have auto-formatting?

**Comment by rod-chapman** [comment]
It's an issue if the auto-format consistently puts the brace so it interferes with out ability to edit the contracts.

**Comment by hanno-becker** [comment]
How does a brace interfere with your ability to edit the contract?

I am hesitant to make any changes here unless we intend to coordinate with MLKEM-C-Generic and MLKEM-C-Embedded.

**Comment by rod-chapman** [comment]
Putting the { on the same line as the contract makes it really hard to add, remove, re-order and generally edit the contracts, which one does _lots_ when developing proofs.

**Comment by hanno-becker** [comment]
@mkannwischer @cothan WDYT?

**Comment by cothan** [comment]
I don't mind switch to BSD style. If Google style get in the way, let's switch to BSD style.

**Comment by rod-chapman** [comment]
CBMC also has a special "==>" operator which is used in quantified expressions. Currently, astyle breaks that by reformatting it to "== >" (with a space after the "==").

I think this means we should also consider removing "--pad-oper" from the .astylerc file.

**Comment by cothan** [comment]
@rod-chapman , once you finalize the changes need for CBMC, feel free to modify .astylerc file and make a PR with reformatted source files.  
The current .asylerc file was inspired from pqclean file, we can always adjust it to our need. CBMC is important than style, imo.

**Comment by mkannwischer** [comment]
I don't mind which style we use as long as it's consistent and we enforce it in CI. 
We can change the astyle configuration to use bsd.

**Comment by rod-chapman** [comment]
I will make this happen atomically when main is reasonably stable. The commit will touch almost all source files, so you'll need to rebase your branches.

**Comment by hanno-becker** [comment]
That's no problem. But yes, agree it should be a standalone PR doing nothing else but the style update.

**Comment by hanno-becker** [comment]
Ok, @rod-chapman fire up a PR when you've got the time.

**Comment by rod-chapman** [comment]
Will do. Just catching up.

**Comment by rod-chapman** [comment]
Doing this now. PR coming soon.

**Comment by cothan** [comment]
Thanks @rod-chapman  for the PR #64 .
