### ISSUE TITLE
`tests bench` script should fail if binaries fail

### ISSUE THREAD

**Issue by hanno-becker** [pq-code-package/mlkem-c-aarch64#70]
**Issue:** `scripts/tests/bench` does not fail if the benchmarking binaries fail.

Example output:
```
~/repos/mlkem-c-aarch64$ ./scripts/tests bench --cycles PERF
INFO  > benchmark
INFO  > make CYCLES=PERF test/bin/bench_kyber512
INFO  > MLKEM512 passed
INFO  > make CYCLES=PERF test/bin/bench_kyber768
INFO  > MLKEM768 passed
INFO  > make CYCLES=PERF test/bin/bench_kyber1024
INFO  > MLKEM1024 passed
MLKEM512

MLKEM768

MLKEM1024
```

Here, the issue was that access to `perf` was missing, as witnessed when running the binaries separately:
```
~/repos/mlkem-c-aarch64$ ./test/bin/bench_kyber1024
read: Bad file descriptor
```

Another issue is that switching between `CYCLES=NO/PMU/PERF` requires `make clean` and rebuild, which is not yet documented.

**Task:**
- [x]  Fix `tests` so that it fails if the test/bench binaries fail. Ideally, don't mask `stderr`.
- [ ] Document that `make clean` is needed when switching between `NO/PERF/PMU`, or -- even better -- detect the switch and rebuild automatically.

**Comment by mkannwischer** [comment]
Thanks. @potsrevennil and I will have a look at this next week. 

The catching of failures is not limited to benchmarks I believe. The rc should also be checked for the other tests, but I guess those have never failed so far.

**Comment by potsrevennil** [comment]
https://github.com/pq-code-package/mlkem-c-aarch64/pull/69 solved the first task by the way.

**Comment by hanno-becker** [comment]
@potsrevennil Noted

**Comment by hanno-becker** [comment]
Superseded by #75
