### ISSUE TITLE
Makefile should properly keep track of variables

### ISSUE THREAD

**Issue by mkannwischer** [pq-code-package/mlkem-c-aarch64#75]
If you are currently running 
```
tests bench
```
(implying `--cycles NO`), followed by 
```
tests bench --cycles PMU
```
it won't work because the Makefile does not properly keep track of those variables and won't rebuild the binaries. 

The way to solve this is to keep the variables of the previous builds in a file and re-build in case any of those change as we have implemented, for example, 
here: https://github.com/pq-code-package/mlkem-c-embedded/blob/e1ab38d94529eb6a43705cf7dd938879b177ea07/mk/config.mk#L22.

**Comment by hanno-becker** [comment]
Overlaps with https://github.com/pq-code-package/mlkem-c-aarch64/issues/70
