### ISSUE TITLE
astyle lint is breaking mlkem/poly.c on branch only

### ISSUE THREAD

**Issue by rod-chapman** [pq-code-package/mlkem-c-aarch64#94]
Application of "astyle" to mlkem/poly.c is failing BUT on the poly_compress_contracts branch only.

On the "main" branch, it works fine, and doesn't change the file at all.

On the "poly_compress_contracts" branch, it destroys the formatting of the file from the poly_decompress() function onwards.]

e.g. in the NIX environment on either MacOS or Linux:
```
git checkout main
cd mlkem
astyle --options=../.astylerc --formatted poly.c
git st .
# reports no change...
git checkout poly_compress_contracts
astyle --options=../.astylerc --formatted poly.c
Formatted  /home/ubuntu/pqcp/refb/mlkem/poly.c
git st .
```
shows poly.c has been modified. `git diff .` shows the file has been reformatted incorrectly.

I am unable to work out what's going wrong here.

**Comment by hanno-becker** [comment]
This was ultimately due to bad indentation in #91.
